#!/bin/sh

# Common script to patch the zshrc generated by Lunar Shell
# This patching process adds support for Ctrl+Left/Right binds,
# Home, End and Del keys. They don't work with stock ZSH config
# unfortunately.

# Lunar-ZSHRC
sudo curl -o /etc/zsh/zshrc -L https://raw.githubusercontent.com/ohemilyy/SysScripts/main/LunarShell/asset/zshrc
