#!/bin/sh

# Common script to patch the zshrc generated by Lunar Shell
# This patching process adds support for Ctrl+Left/Right binds,
# Home, End and Del keys. They don't work with stock ZSH config
# unfortunately.

# Lunar-ZSHRC
cd /
sudo patch -p1 < <(curl -s https://raw.githubusercontent.com/kurtbahartr/config-packages/master/patches/lunar-zshrc.patch)
